
package sin.glouds.test.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsTest", targetNamespace = "http://webservice.test.glouds.sin/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsTest {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAge", targetNamespace = "http://webservice.test.glouds.sin/", className = "sin.glouds.test.webservice.GetAge")
    @ResponseWrapper(localName = "getAgeResponse", targetNamespace = "http://webservice.test.glouds.sin/", className = "sin.glouds.test.webservice.GetAgeResponse")
    @Action(input = "http://webservice.test.glouds.sin/WsTest/getAgeRequest", output = "http://webservice.test.glouds.sin/WsTest/getAgeResponse")
    public int getAge();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getString", targetNamespace = "http://webservice.test.glouds.sin/", className = "sin.glouds.test.webservice.GetString")
    @ResponseWrapper(localName = "getStringResponse", targetNamespace = "http://webservice.test.glouds.sin/", className = "sin.glouds.test.webservice.GetStringResponse")
    @Action(input = "http://webservice.test.glouds.sin/WsTest/getStringRequest", output = "http://webservice.test.glouds.sin/WsTest/getStringResponse")
    public String getString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
